#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = ["pyyaml>=6.0"]
# ///
"""okf.py - configure, audit, and adapt folders as Open Knowledge Format (OKF) v0.2 bundles.

Spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md

Commands:
  init  ROOT              Scaffold a bundle (root index.md declaring okf_version, log.md).
  new   ROOT PATH         Create a concept with valid frontmatter (templates per type).
  index ROOT              Generate/refresh index.md files from concept frontmatter.
  log   ROOT              Add a dated entry to a log.md (newest-first).
  audit ROOT              Conformance (spec section 11) + lint of SHOULD-level guidance.
  plan  ROOT              Survey an existing folder; write a reviewable JSON plan of edits.
  apply PLAN              Apply a (reviewed) plan. Use --dry-run first.

Run with `uv run scripts/okf.py ...` (PyYAML installed automatically) or plain
`python3` when PyYAML is available.
"""
import argparse
import fnmatch
import json
import os
import posixpath
import re
import subprocess
import sys
import urllib.parse
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("okf.py needs PyYAML. Run it with `uv run scripts/okf.py ...` or `pip install pyyaml`.")

OKF_VERSION = "0.2"
RESERVED = ("index.md", "log.md")
DEFAULT_EXCLUDES = ("node_modules", "__pycache__", "venv")
GEN_MARKER = "<!-- okf:generated"
GEN_LINE = "<!-- okf:generated by okf.py index - edits are overwritten; delete this line to hand-curate -->"
STATUSES = ("draft", "stable", "deprecated")
AC_TYPE = "Attested Computation"

ACTOR_RE = re.compile(r"^(human:\S+|process:\S+|[^\s/:]+/\S+)$")
ISO_DT_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
SCHEME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")
FM_RE = re.compile(r"\A﻿?---[ \t]*\r?\n(.*?)^---[ \t]*\r?$\n?", re.S | re.M)
FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})[^\n]*\n.*?^ {0,3}\1[^\n]*$", re.S | re.M)
INLINE_CODE_RE = re.compile(r"`[^`\n]*`")
LINK_RE = re.compile(r"\[[^\]]*\]\(\s*<?([^)\s>]+)>?(?:\s+\"[^\"]*\")?\s*\)")
LIST_LINK_RE = re.compile(r"^\s*[*+-]\s+\[[^\]]+\]\(([^)\s]+)\)(?:\s*-\s*(.*))?$", re.M)
HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$", re.M)
FN_REF_RE = re.compile(r"\[\^([^\]\s]+)\](?!:)")
FN_DEF_RE = re.compile(r"^\[\^([^\]\s]+)\]:", re.M)


# --------------------------------------------------------------------------- YAML


class _Loader(yaml.SafeLoader):
    """SafeLoader that keeps datetimes as strings so we can check the raw form."""


_Loader.yaml_implicit_resolvers = {
    ch: [(tag, rx) for tag, rx in rs if tag != "tag:yaml.org,2002:timestamp"]
    for ch, rs in yaml.SafeLoader.yaml_implicit_resolvers.items()
}


def yload(s):
    return yaml.load(s, Loader=_Loader)


def _scalar(v):
    return v is None or isinstance(v, (str, int, float, bool))


def ys(v, flow=False):
    """Emit a YAML scalar, quoting only when a plain scalar would not round-trip."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v)
    try:
        probe = yload("{k: %s}" % s if flow else "k: %s" % s)
        ok = probe == {"k": s}
    except yaml.YAMLError:
        ok = False
    if not s or s != s.strip() or "#" in s or "\n" in s or (flow and any(c in s for c in ",[]{}")):
        ok = False
    return s if ok else json.dumps(s, ensure_ascii=False)


def emit(key, v, ind=0):
    """Emit one frontmatter key in the house style used by the OKF spec examples."""
    pad = "  " * ind
    if _scalar(v):
        return [f"{pad}{key}: {ys(v)}"]
    if isinstance(v, list) and all(_scalar(x) for x in v):
        return [f"{pad}{key}: [{', '.join(ys(x, True) for x in v)}]"]
    if isinstance(v, dict) and key in ("generated", "usage_window") and all(_scalar(x) for x in v.values()):
        return [f"{pad}{key}: {_flow_map(v)}"]
    out = [f"{pad}{key}:"]
    if isinstance(v, dict):
        for k, x in v.items():
            out += emit(k, x, ind + 1)
        return out
    for item in v:
        if isinstance(item, dict) and len(item) <= 3 and all(_scalar(x) for x in item.values()):
            out.append(f"{pad}  - {_flow_map(item)}")
        elif isinstance(item, dict):
            sub = []
            for k, x in item.items():
                sub += emit(k, x, ind + 2)
            sub[0] = f"{pad}  - " + sub[0].lstrip()
            out += sub
        else:
            out.append(f"{pad}  - {ys(item)}")
    return out


def _flow_map(d):
    return "{ " + ", ".join(f"{k}: {ys(x, True)}" for k, x in d.items()) + " }"


def emit_block(fields):
    lines = []
    for k, v in fields.items():
        lines += emit(k, v)
    return "---\n" + "\n".join(lines) + "\n---\n"


# --------------------------------------------------------------------------- docs & bundle


@dataclass
class Doc:
    rel: str
    text: str
    has_fm: bool = False
    fm_raw: str = ""
    fm: object = None
    fm_error: str = ""
    body: str = ""
    body_line: int = 1


def parse_doc(rel, text):
    d = Doc(rel, text)
    m = FM_RE.match(text)
    if not m:
        d.body = text.lstrip("﻿")
        return d
    d.has_fm, d.fm_raw, d.body = True, m.group(1), text[m.end():]
    d.body_line = text[: m.end()].count("\n") + 1
    try:
        d.fm = yload(d.fm_raw) if d.fm_raw.strip() else {}
    except yaml.YAMLError as e:
        d.fm_error = " ".join(str(e).split())[:240]
    return d


def fm_dict(d):
    return d.fm if isinstance(d.fm, dict) else {}


def fm_line(d, key):
    for i, line in enumerate(d.fm_raw.splitlines()):
        if re.match(rf"^{re.escape(key)}\s*:", line):
            return i + 2
    return 1


def strip_code(text):
    """Blank out fenced and inline code, preserving offsets and line numbers."""
    blank = lambda m: re.sub(r"[^\n]", " ", m.group(0))  # noqa: E731
    return INLINE_CODE_RE.sub(blank, FENCE_RE.sub(blank, text))


def rjoin(a, b):
    return f"{a}/{b}" if a else b


def humanize(name):
    stem = re.sub(r"\.md$", "", name)
    words = re.sub(r"[-_]+", " ", stem).strip()
    return words[:1].upper() + words[1:] if words else stem


def is_concept(rel):
    return posixpath.basename(rel) not in RESERVED


class Bundle:
    def __init__(self, root, excludes=()):
        self.root = os.path.abspath(root)
        if not os.path.isdir(self.root):
            sys.exit(f"Not a directory: {root}")
        self.dirs, self.docs, self.unreadable = {}, {}, []
        for dirpath, dirnames, filenames in os.walk(self.root):
            rel_dir = os.path.relpath(dirpath, self.root).replace(os.sep, "/")
            rel_dir = "" if rel_dir == "." else rel_dir
            dirnames[:] = sorted(n for n in dirnames if not self._excluded(n, rjoin(rel_dir, n), excludes))
            mds = sorted(n for n in filenames if n.endswith(".md") and not self._excluded(n, rjoin(rel_dir, n), excludes))
            self.dirs[rel_dir] = (list(dirnames), mds)
            for n in mds:
                rel = rjoin(rel_dir, n)
                try:
                    with open(os.path.join(self.root, rel), encoding="utf-8") as f:
                        self.docs[rel] = parse_doc(rel, f.read())
                except UnicodeDecodeError:
                    self.unreadable.append(rel)

    @staticmethod
    def _excluded(name, rel, excludes):
        if name.startswith(".") or name in DEFAULT_EXCLUDES:
            return True
        return any(fnmatch.fnmatch(rel, g) or fnmatch.fnmatch(name, g) for g in excludes)

    def concepts(self):
        return {r: d for r, d in self.docs.items() if is_concept(r)}

    def exists(self, rel):
        return os.path.exists(os.path.join(self.root, rel))

    def subtree_concepts(self, rel_dir):
        pre = rel_dir + "/" if rel_dir else ""
        return [r for r in self.docs if r.startswith(pre) and is_concept(r)]

    def abs(self, rel):
        return os.path.join(self.root, rel)


def resolve(src_rel, target, from_root=False):
    """Bundle-relative path for a link/path value; None if external; '..' prefix if outside."""
    t = target.split("#", 1)[0].split("?", 1)[0]
    if not t or SCHEME_RE.match(t) or t.startswith("//"):
        return None
    t = urllib.parse.unquote(t)
    if t.startswith("/"):
        p = t.lstrip("/")
    elif from_root:
        p = t
    else:
        p = posixpath.join(posixpath.dirname(src_rel), t)
    p = posixpath.normpath(p)
    return "" if p == "." else p


def parse_dt(s):
    if not isinstance(s, str) or not ISO_DT_RE.match(s):
        return None
    s = s.replace("Z", "+00:00")
    s = re.sub(r"([+-]\d{2})(\d{2})$", r"\1:\2", s)
    s = re.sub(r"\.(\d+)", lambda m: "." + (m.group(1) + "000000")[:6], s)
    try:
        return datetime.fromisoformat(s)
    except ValueError:
        return None


def utc_z(dt):
    return dt.astimezone(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")


def now_utc():
    return datetime.now(timezone.utc)


def trust_tier(fm):
    v = fm.get("verified")
    if isinstance(v, dict):
        v = [v]
    if not isinstance(v, list) or not v:
        return "unverified"
    bys = [str(e.get("by", "")) for e in v if isinstance(e, dict)]
    return "human-reviewed" if any(b.startswith("human:") for b in bys) else "machine-confirmed"


def find_section(body, title_re):
    """(heading_start, section_end) of the first section whose heading matches title_re."""
    s = strip_code(body)
    for m in HEADING_RE.finditer(s):
        if re.fullmatch(title_re, m.group(2).strip(), re.I):
            level = len(m.group(1))
            nxt = re.compile(rf"^#{{1,{level}}}[ \t]+\S", re.M).search(s, m.end())
            return m.start(), (nxt.start() if nxt else len(body))
    return None


# --------------------------------------------------------------------------- audit


@dataclass
class Finding:
    severity: str
    code: str
    path: str
    message: str
    line: int = 0


SEV_ORDER = {"error": 0, "warning": 1, "info": 2}


def audit(b, now):
    out = []

    def add(sev, code, path, msg, line=0):
        out.append(Finding(sev, code, path, msg, line))

    for rel in b.unreadable:
        add("error", "not-utf8", rel, "File is not UTF-8; OKF concepts must be UTF-8 markdown (spec 4).")

    for rel, d in sorted(b.concepts().items()):
        _audit_concept(b, d, add, now)

    for rel_dir in sorted(b.dirs):
        _audit_reserved(b, rel_dir, add)

    out.sort(key=lambda f: (SEV_ORDER[f.severity], f.path, f.line, f.code))
    return out, _summary(b, out, now)


def _check_dt(add, rel, line, key, val):
    if parse_dt(val) is None:
        add("warning", "bad-datetime", rel,
            f"`{key}` must be an ISO 8601 datetime with an explicit UTC offset, e.g. 2026-06-30T14:00:00Z (got {val!r}).", line)
        return None
    return parse_dt(val)


def _check_actor(add, rel, line, key, val):
    if not isinstance(val, str) or not ACTOR_RE.match(val):
        add("warning", "bad-actor", rel,
            f"`{key}` should be an actor: `<producer>/<version>`, `human:<id>`, or `process:<id>` (got {val!r}) (spec 7).", line)


def _check_path(b, add, d, key, val, line):
    if not isinstance(val, str) or not val.strip():
        add("warning", "missing-path-target", d.rel, f"`{key}` should be a path or URL.", line)
        return
    p = resolve(d.rel, val)
    if p is None:
        return
    if p.startswith(".."):
        add("warning", "path-outside-bundle", d.rel, f"`{key}` ({val}) points outside the bundle.", line)
    elif b.exists(p):
        return
    elif not val.startswith("/") and b.exists(resolve(d.rel, val, from_root=True)):
        add("info", "path-resolved-from-root", d.rel,
            f"`{key}` ({val}) only exists relative to the bundle root; write `/{val}` so it resolves unambiguously (spec 6.2).", line)
    else:
        add("warning", "missing-path-target", d.rel, f"`{key}` ({val}) does not exist in the bundle.", line)


def _audit_concept(b, d, add, now):
    rel = d.rel
    name = posixpath.basename(rel)
    if name.lower() in RESERVED:
        add("info", "reserved-name-case", rel, f"`{name}` differs from reserved `{name.lower()}` only by case; avoid confusion.")
    if not d.has_fm:
        add("error", "missing-frontmatter", rel, "No YAML frontmatter; every concept needs at least `type` (spec 4.1, 11).", 1)
    elif d.fm_error:
        add("error", "invalid-frontmatter", rel, f"Frontmatter is not parseable YAML: {d.fm_error}", 1)
    elif not isinstance(d.fm, dict):
        add("error", "invalid-frontmatter", rel, "Frontmatter must be a YAML mapping.", 1)
    fm = fm_dict(d)
    if isinstance(d.fm, dict) or (d.has_fm and not d.fm_error and d.fm == {}):
        t = fm.get("type")
        if not isinstance(t, str) or not t.strip():
            add("error", "missing-type", rel, "Frontmatter needs a non-empty string `type` (spec 4.1, 11).", fm_line(d, "type"))
        if "title" not in fm:
            add("info", "missing-title", rel, "No `title` (recommended; consumers fall back to the filename).")
        desc = fm.get("description")
        if desc is None:
            add("warning", "missing-description", rel, "No `description` (recommended; used by index.md, search, previews).")
        elif not isinstance(desc, str):
            add("warning", "missing-description", rel, "`description` should be a one-line string.", fm_line(d, "description"))
        elif "\n" in desc.strip() or len(desc) > 240:
            add("info", "long-description", rel, "`description` should be a single sentence.", fm_line(d, "description"))
        if "tags" in fm and not (isinstance(fm["tags"], list) and all(isinstance(x, str) for x in fm["tags"])):
            add("warning", "tags-not-list", rel, "`tags` should be a YAML list of strings, e.g. [sales, revenue].", fm_line(d, "tags"))
        if "status" in fm and fm["status"] not in STATUSES:
            add("warning", "invalid-status", rel, f"`status` must be one of {', '.join(STATUSES)} (got {fm['status']!r}).", fm_line(d, "status"))
        if "stale_after" in fm:
            dt = _check_dt(add, rel, fm_line(d, "stale_after"), "stale_after", fm["stale_after"])
            if dt and now >= dt:
                add("warning", "stale", rel, f"Stale since {fm['stale_after']} (now >= stale_after); re-verify and push it forward (spec 5.5).", fm_line(d, "stale_after"))
        if "timestamp" in fm:
            add("warning", "legacy-timestamp", rel, "v0.1 `timestamp` is superseded by `generated: { by, at }` (spec 13.1).", fm_line(d, "timestamp"))
        _audit_trust(d, fm, add)
        source_ids = _audit_sources(d, fm, add)
        if fm.get("type") == AC_TYPE:
            _audit_ac(b, d, fm, add)
    else:
        source_ids = set()
    _audit_body(b, d, add, source_ids)


def _audit_trust(d, fm, add):
    rel = d.rel
    if "generated" in fm:
        g, ln = fm["generated"], fm_line(d, "generated")
        if not isinstance(g, dict):
            add("warning", "bad-generated", rel, "`generated` should be a mapping `{ by, at }` (spec 5.2).", ln)
        else:
            if "by" not in g:
                add("warning", "bad-generated", rel, "`generated.by` is required within `generated` (spec 5.2).", ln)
            else:
                _check_actor(add, rel, ln, "generated.by", g["by"])
            if "at" in g:
                _check_dt(add, rel, ln, "generated.at", g["at"])
    if "verified" in fm:
        v, ln = fm["verified"], fm_line(d, "verified")
        entries = [v] if isinstance(v, dict) else v
        if not isinstance(entries, list):
            add("warning", "bad-verified", rel, "`verified` should be a list of `{ by, at }` (or one mapping) (spec 5.2).", ln)
            return
        for e in entries:
            if not isinstance(e, dict) or "by" not in e or "at" not in e:
                add("warning", "bad-verified", rel, f"Each `verified` entry needs `by` and `at` (got {e!r}).", ln)
                continue
            _check_actor(add, rel, ln, "verified.by", e["by"])
            _check_dt(add, rel, ln, "verified.at", e["at"])


def _audit_sources(d, fm, add):
    rel, ids = d.rel, set()
    if "usage_window" in fm:
        _check_window(add, rel, fm_line(d, "usage_window"), fm["usage_window"])
    if "sources" not in fm:
        return ids
    src, ln = fm["sources"], fm_line(d, "sources")
    if not isinstance(src, list):
        add("warning", "bad-sources", rel, "`sources` should be a list of entries with `resource` (spec 5.1).", ln)
        return ids
    for e in src:
        if not isinstance(e, dict) or not e.get("resource"):
            add("warning", "bad-sources", rel, f"Each `sources` entry needs a `resource` (got {e!r}).", ln)
            continue
        sid = e.get("id")
        if sid is not None:
            if str(sid) in ids:
                add("warning", "duplicate-source-id", rel, f"Duplicate sources id `{sid}`.", ln)
            ids.add(str(sid))
        if "usage_count" in e and not (isinstance(e["usage_count"], int) and not isinstance(e["usage_count"], bool) and e["usage_count"] >= 0):
            add("warning", "bad-sources", rel, f"`usage_count` should be a non-negative integer (source {sid or e['resource']}).", ln)
        if "usage_count" in e and "usage_window" not in fm and "usage_window" not in e:
            add("info", "usage-without-window", rel, f"`usage_count` on {sid or e['resource']} has no `usage_window` framing it (spec 5.1).", ln)
        if "last_modified" in e:
            _check_dt(add, rel, ln, "sources.last_modified", e["last_modified"])
        if "usage_window" in e:
            _check_window(add, rel, ln, e["usage_window"])
    return ids


def _check_window(add, rel, ln, w):
    if not isinstance(w, dict) or "from" not in w or "to" not in w:
        add("warning", "bad-sources", rel, "`usage_window` should be `{ from, to }` datetimes (spec 5.1).", ln)
        return
    _check_dt(add, rel, ln, "usage_window.from", w["from"])
    _check_dt(add, rel, ln, "usage_window.to", w["to"])


def _audit_ac(b, d, fm, add):
    rel = d.rel
    if not fm.get("runtime"):
        add("warning", "ac-missing-runtime", rel, "Attested Computation requires `runtime` (spec 10.2).", 1)
    params = fm.get("parameters")
    if params is not None:
        good = isinstance(params, list) and all(
            isinstance(p, dict) and {"name", "type", "required"} <= set(p) for p in params)
        if not good:
            add("warning", "ac-bad-parameters", rel, "`parameters` entries need `{ name, type, required }` (spec 10.2).", fm_line(d, "parameters"))
    sec = find_section(d.body, "computation")
    fences = 0
    if sec:
        section = d.body[sec[0]:sec[1]]
        fences = len(FENCE_RE.findall(section)) or (1 if re.search(r"(^|\n)\s*\n(?: {4}|\t)\S", section) else 0)
    if "computation" in fm:
        _check_path(b, add, d, "computation", fm["computation"], fm_line(d, "computation"))
        if fences:
            add("warning", "ac-ambiguous-computation", rel, "Both `computation` and an inline `# Computation` block; use one (spec 10.3).")
    elif not fences:
        add("warning", "ac-no-computation", rel, "No computation: add a fenced block under `# Computation` or set `computation:` to a file (spec 10.3).")
    elif fences > 1:
        add("warning", "ac-multiple-fences", rel, "`# Computation` should hold a single fenced code block (spec 10.3).")
    for part in ("executor", "attester"):
        v = fm.get(part)
        if v is None:
            add("info", f"ac-no-{part}", rel, f"No `{part}`; consumers can't {'run' if part == 'executor' else 'check'} this computation (spec 10.2).")
            continue
        if not isinstance(v, dict) or not v.get("resource"):
            add("warning", f"ac-bad-{part}", rel, f"`{part}` needs a `resource` (spec 10.2).", fm_line(d, part))
            continue
        _check_path(b, add, d, f"{part}.resource", v["resource"], fm_line(d, part))
        if part == "executor" and not isinstance(v.get("receipt"), list):
            add("warning", "ac-bad-executor", rel, "`executor.receipt` should list the fields a run returns, e.g. [job_id, executed_sql, result].", fm_line(d, part))


def _audit_body(b, d, add, source_ids):
    rel, s = d.rel, strip_code(d.body)
    if find_section(d.body, "citations"):
        add("warning", "legacy-citations", rel, "v0.1 `# Citations` list is superseded by frontmatter `sources` + keyed footnotes (spec 13.1).")
    labels = set(FN_REF_RE.findall(s)) | set(FN_DEF_RE.findall(s))
    if labels and source_ids:
        for lab in sorted(labels - source_ids):
            add("warning", "footnote-unkeyed", rel, f"Footnote [^{lab}] matches no `sources[].id`; key footnotes to source ids (spec 5.1).")
    elif labels and not source_ids:
        add("info", "footnotes-without-sources", rel, "Body has footnotes but no keyed `sources`; move attribution to `sources` with ids (spec 5.1).")
    for m in LINK_RE.finditer(s):
        p = resolve(rel, m.group(1))
        if p is None or p.startswith(".."):
            continue
        if not b.exists(p):
            line = d.body_line + s.count("\n", 0, m.start())
            add("info", "broken-link", rel, f"Link target `{m.group(1)}` does not exist (tolerated: may be unwritten knowledge) (spec 6.1).", line)


def _audit_reserved(b, rel_dir, add):
    subdirs, mds = b.dirs[rel_dir]
    idx_rel, log_rel = rjoin(rel_dir, "index.md"), rjoin(rel_dir, "log.md")
    has_concepts = bool(b.subtree_concepts(rel_dir))
    if idx_rel in b.docs:
        d = b.docs[idx_rel]
        if d.has_fm:
            fm = fm_dict(d)
            if rel_dir:
                add("error", "index-frontmatter", idx_rel, "Only the bundle-root index.md may carry frontmatter (spec 8).", 1)
            elif d.fm_error or not isinstance(d.fm, dict) or set(fm) - {"okf_version"}:
                add("error", "index-frontmatter", idx_rel, "Root index.md frontmatter may only hold `okf_version` (spec 8, 12).", 1)
            elif "okf_version" in fm and not isinstance(fm["okf_version"], str):
                add("warning", "okf-version-unquoted", idx_rel, 'Quote the version so YAML keeps it a string: okf_version: "0.2".', 2)
        s = strip_code(d.body)
        items = LIST_LINK_RE.findall(s)
        if has_concepts and (not items or not HEADING_RE.search(s)):
            add("warning", "index-structure", idx_rel, "index.md should be headed sections of `* [Title](url) - description` items (spec 8).")
        linked = {resolve(idx_rel, u) for u, _ in items} | {resolve(idx_rel, u) for u in LINK_RE.findall(s)}
        linked = {p.rstrip("/") for p in linked if p is not None}
        linked |= {posixpath.dirname(p) for p in linked if p.endswith("/index.md") or p.endswith("index.md")}
        for f in mds:
            r = rjoin(rel_dir, f)
            if is_concept(r) and r not in linked:
                add("warning", "index-missing-entry", idx_rel, f"Concept `{f}` is not listed; run `okf.py index` or add it.")
        for sd in subdirs:
            r = rjoin(rel_dir, sd)
            if b.subtree_concepts(r) and r not in linked:
                add("warning", "index-missing-entry", idx_rel, f"Subdirectory `{sd}/` is not listed.")
        for u, _ in items:
            p = resolve(idx_rel, u)
            if p is not None and not p.startswith("..") and not b.exists(p):
                add("warning", "index-dead-entry", idx_rel, f"Entry `{u}` points to a missing file.")
    elif rel_dir == "":
        add("info", "no-root-index", idx_rel, "No root index.md; run `okf.py index` to add one and declare okf_version (spec 8, 12).")
    if log_rel in b.docs:
        d = b.docs[log_rel]
        if d.has_fm:
            add("warning", "log-frontmatter", log_rel, "log.md should have no frontmatter (spec 9).", 1)
        s = strip_code(d.body)
        dates = []
        for m in re.finditer(r"^##[ \t]+(.+?)[ \t]*$", s, re.M):
            h = m.group(1).strip()
            line = d.body_line + s.count("\n", 0, m.start())
            if not DATE_RE.match(h):
                add("error", "log-bad-date", log_rel, f"Log date headings MUST be YYYY-MM-DD (got `## {h}`) (spec 9).", line)
            else:
                dates.append(h)
        if dates != sorted(dates, reverse=True):
            add("warning", "log-order", log_rel, "Log entries should be newest first (spec 9).")


def _summary(b, findings, now):
    concepts = b.concepts()
    fms = {r: fm_dict(d) for r, d in concepts.items()}
    root_idx = b.docs.get("index.md")
    version = fm_dict(root_idx).get("okf_version") if root_idx else None
    sev = Counter(f.severity for f in findings)
    stale = sorted(r for r, fm in fms.items() if (dt := parse_dt(fm.get("stale_after"))) and now >= dt)
    return {
        "root": b.root,
        "okf_version": None if version is None else str(version),
        "conformant": sev["error"] == 0,
        "concepts": len(concepts),
        "errors": sev["error"],
        "warnings": sev["warning"],
        "info": sev["info"],
        "by_type": dict(Counter(str(fm.get("type") or "(none)") for fm in fms.values()).most_common()),
        "trust_tiers": dict(Counter(trust_tier(fm) for fm in fms.values())),
        "status": dict(Counter(str(fm.get("status", "stable")) for fm in fms.values())),
        "stale": stale,
        "attested_computations": sum(1 for fm in fms.values() if fm.get("type") == AC_TYPE),
        "with_sources": sum(1 for fm in fms.values() if fm.get("sources")),
        "with_generated": sum(1 for fm in fms.values() if fm.get("generated")),
        "directories_without_index": sum(1 for r in b.dirs if b.subtree_concepts(r) and rjoin(r, "index.md") not in b.docs),
    }


def cmd_audit(a):
    b = Bundle(a.root, a.exclude)
    now = parse_dt(a.now) if a.now else now_utc()
    findings, summary = audit(b, now)
    if a.json:
        print(json.dumps({"summary": summary, "findings": [asdict(f) for f in findings]}, indent=2))
    else:
        _print_audit(summary, findings, a.min_severity, a.max_per_code)
    if summary["errors"] or (a.strict and summary["warnings"]):
        return 1
    return 0


def _print_audit(s, findings, min_sev, max_per_code):
    verdict = "CONFORMANT" if s["conformant"] else "NOT CONFORMANT"
    print(f"OKF audit: {s['root']}  (okf_version: {s['okf_version'] or 'undeclared'})")
    print(f"  {s['concepts']} concepts | {s['errors']} errors | {s['warnings']} warnings | {s['info']} info -> {verdict} (OKF v{OKF_VERSION}, spec 11)")
    if s["by_type"]:
        print("  types:  " + ", ".join(f"{k} {v}" for k, v in s["by_type"].items()))
    print("  trust:  " + ", ".join(f"{k} {s['trust_tiers'].get(k, 0)}" for k in ("unverified", "machine-confirmed", "human-reviewed")))
    print("  status: " + ", ".join(f"{k} {v}" for k, v in s["status"].items()) + f" | stale {len(s['stale'])}")
    print(f"  provenance: {s['with_sources']} with sources, {s['with_generated']} with generated | "
          f"attested computations {s['attested_computations']} | dirs without index.md {s['directories_without_index']}")
    shown = [f for f in findings if SEV_ORDER[f.severity] <= SEV_ORDER[min_sev]]
    per_code, hidden = Counter(), Counter()
    current = None
    for f in shown:
        per_code[f.code] += 1
        if max_per_code and per_code[f.code] > max_per_code:
            hidden[f.code] += 1
            continue
        if f.severity != current:
            current = f.severity
            print(f"\n{f.severity.upper()}S")
        loc = f"{f.path}:{f.line}" if f.line else f.path
        print(f"  {loc}  [{f.code}] {f.message}")
    for code, n in sorted(hidden.items()):
        print(f"  ... and {n} more [{code}] (use --json or --max-per-code 0 for all)")
    below = len(findings) - len(shown)
    if below:
        print(f"\n({below} lower-severity findings hidden; use --min-severity info)")


# --------------------------------------------------------------------------- index


def concept_title(d):
    fm = fm_dict(d)
    if isinstance(fm.get("title"), str) and fm["title"].strip():
        return fm["title"].strip()
    m = re.search(r"^#[ \t]+(.+?)[ \t]*#*[ \t]*$", strip_code(d.body), re.M)
    return m.group(1).strip() if m else humanize(posixpath.basename(d.rel))


def _esc(s):
    return s.replace("[", "\\[").replace("]", "\\]")


def _entry(title, url, desc):
    line = f"* [{_esc(title)}]({url})"
    if desc:
        line += " - " + " ".join(str(desc).split())
    return line


def build_index(b, rel_dir, group_by, version):
    subdirs, mds = b.dirs[rel_dir]
    concepts = [b.docs[rjoin(rel_dir, f)] for f in mds if is_concept(f) and rjoin(rel_dir, f) in b.docs]
    groups = {}
    deprecated = []
    for d in sorted(concepts, key=lambda d: concept_title(d).lower()):
        fm = fm_dict(d)
        e = _entry(concept_title(d), posixpath.basename(d.rel), fm.get("description"))
        if fm.get("status") == "deprecated":
            deprecated.append(e)
            continue
        key = str(fm.get("type") or "Concepts") if group_by == "type" else "Concepts"
        groups.setdefault(key, []).append(e)
    dir_entries = []
    for sd in subdirs:
        r = rjoin(rel_dir, sd)
        sub = b.subtree_concepts(r)
        if not sub:
            continue
        desc = None
        for cand in ("README.md", "overview.md", f"{sd}.md"):
            cd = b.docs.get(rjoin(r, cand))
            if cd and isinstance(fm_dict(cd).get("description"), str):
                desc = fm_dict(cd)["description"]
                break
        if not desc:
            types = Counter(str(fm_dict(b.docs[x]).get("type") or "untyped") for x in sub)
            desc = f"{len(sub)} concept{'s' * (len(sub) != 1)} ({', '.join(t for t, _ in types.most_common(3))})"
        dir_entries.append(_entry(humanize(sd), f"{sd}/", desc))
    parts = []
    if version:
        parts.append(f'---\nokf_version: "{version}"\n---\n')
    parts.append(GEN_LINE + "\n")
    for key in sorted(groups):
        parts.append(f"# {key}\n\n" + "\n".join(groups[key]) + "\n")
    if dir_entries:
        parts.append("# Directories\n\n" + "\n".join(dir_entries) + "\n")
    if deprecated:
        parts.append("# Deprecated\n\n" + "\n".join(deprecated) + "\n")
    if not groups and not dir_entries and not deprecated:
        parts.append("# Concepts\n\n_No concepts yet. Add one with `okf.py new`._\n")
    return "\n".join(parts)


def cmd_index(a):
    b = Bundle(a.root, a.exclude)
    root_idx = b.docs.get("index.md")
    existing_version = fm_dict(root_idx).get("okf_version") if root_idx else None
    version = None if a.no_version else (a.okf_version or (str(existing_version) if existing_version else OKF_VERSION))
    changed, skipped, unchanged = [], [], 0
    for rel_dir in sorted(b.dirs):
        if not b.subtree_concepts(rel_dir) and rel_dir != "":
            continue
        rel = rjoin(rel_dir, "index.md")
        content = build_index(b, rel_dir, a.group_by, version if rel_dir == "" else None)
        old = b.docs[rel].text if rel in b.docs else None
        if old is not None and GEN_MARKER not in old and not a.force:
            skipped.append(rel)
            continue
        if old == content:
            unchanged += 1
            continue
        changed.append(rel)
        if not a.check:
            with open(b.abs(rel), "w", encoding="utf-8") as f:
                f.write(content)
    verb = "would update" if a.check else "wrote"
    for r in changed:
        print(f"{verb} {r}")
    for r in skipped:
        print(f"skipped {r} (hand-curated: no okf:generated marker; --force to overwrite)")
    print(f"{len(changed)} {verb}, {unchanged} unchanged, {len(skipped)} skipped")
    return 1 if a.check and changed else 0


# --------------------------------------------------------------------------- init / new / log


def add_log_entry(path, date, kind, message):
    lines = open(path, encoding="utf-8").read().splitlines() if os.path.exists(path) else ["# Update Log", ""]
    entry = f"* **{kind}**: {message}"
    heads = [(i, l[3:].strip()) for i, l in enumerate(lines) if l.startswith("## ")]
    for n, (i, h) in enumerate(heads):
        if h == date:
            end = heads[n + 1][0] if n + 1 < len(heads) else len(lines)
            while end > i + 1 and not lines[end - 1].strip():
                end -= 1
            lines.insert(end, entry)
            break
        if DATE_RE.match(h) and h < date:
            lines[i:i] = [f"## {date}", entry, ""]
            break
    else:
        while lines and not lines[-1].strip():
            lines.pop()
        lines += ["", f"## {date}", entry]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip("\n") + "\n")


def cmd_init(a):
    os.makedirs(a.root, exist_ok=True)
    log = os.path.join(a.root, "log.md")
    if os.path.exists(log):
        print("kept existing log.md")
    else:
        add_log_entry(log, a.date or now_utc().strftime("%Y-%m-%d"), "Initialization", "Created bundle structure.")
        print("wrote log.md")
    idx = os.path.join(a.root, "index.md")
    if os.path.exists(idx):
        print("kept existing index.md (run `okf.py index` to refresh)")
    else:
        b = Bundle(a.root)
        with open(idx, "w", encoding="utf-8") as f:
            f.write(build_index(b, "", "none", a.okf_version))
        print(f'wrote index.md (okf_version "{a.okf_version}")')
    return 0


BODY_TEMPLATES = [
    (r"table|dataset|view|api|endpoint|schema", "# Schema\n\n| Field | Type | Description |\n|-------|------|-------------|\n|  |  |  |\n\n# Examples\n\n"),
    (r"playbook|runbook", "# Trigger\n\n\n# Steps\n\n1. \n"),
    (r"metric|kpi", "# Definition\n\n"),
    (r"decision|adr", "# Context\n\n\n# Decision\n\n\n# Consequences\n\n"),
]

RECEIPTS = {"bigquery": ["job_id", "executed_sql", "result"], "postgres": ["executed_sql", "result"],
            "dbt": ["run_id", "compiled_sql", "result"], "python": ["run_id", "code_hash", "result"]}


def cmd_new(a):
    rel = a.path if a.path.endswith(".md") else a.path + ".md"
    rel = rel.lstrip("/")
    if posixpath.basename(rel) in RESERVED:
        sys.exit(f"{posixpath.basename(rel)} is reserved (spec 3.1); pick another filename.")
    path = os.path.join(a.root, rel)
    if os.path.exists(path):
        sys.exit(f"{rel} already exists.")
    fm = {"type": a.type, "title": a.title or humanize(posixpath.basename(rel))}
    if a.description:
        fm["description"] = a.description
    if a.resource:
        fm["resource"] = a.resource
    if a.tags:
        fm["tags"] = [t.strip() for t in a.tags.split(",") if t.strip()]
    if a.status:
        fm["status"] = a.status
    body = "# Overview\n\n"
    if a.type == AC_TYPE:
        if not a.runtime:
            sys.exit("Attested Computation requires --runtime (e.g. bigquery, postgres, dbt, python).")
        fm["runtime"] = a.runtime
        fm["parameters"] = [{"name": "TODO", "type": "string", "required": True}]
        fm["executor"] = {"resource": "/references/executors/TODO.md", "receipt": RECEIPTS.get(a.runtime, ["run_id", "result"])}
        fm["attester"] = {"resource": "/references/attesters/TODO.py"}
        lang = {"bigquery": "sql", "postgres": "sql", "dbt": "sql"}.get(a.runtime, a.runtime)
        body = (f"# Computation\n\n```{lang}\n-- TODO: the sanctioned computation. Bind ONLY the declared parameters.\n```\n\n"
                "Explain what this computes and cite its policy source with a keyed footnote.\n")
    else:
        for pat, tmpl in BODY_TEMPLATES:
            if re.search(pat, a.type, re.I):
                body = tmpl
                break
    if a.by:
        fm["generated"] = {"by": a.by, "at": utc_z(now_utc())}
    if a.stale_after:
        fm["stale_after"] = a.stale_after
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(emit_block(fm) + "\n" + body)
    print(f"wrote {rel}")
    if a.log:
        add_log_entry(os.path.join(a.root, "log.md"), now_utc().strftime("%Y-%m-%d"), "Creation",
                      f"Established [{fm['title']}](/{rel}).")
        print("logged in log.md")
    return 0


def cmd_log(a):
    path = os.path.join(a.root, a.dir or "", "log.md")
    date = a.date or now_utc().strftime("%Y-%m-%d")
    if not DATE_RE.match(date):
        sys.exit("--date must be YYYY-MM-DD")
    add_log_entry(path, date, a.kind, a.message)
    print(f"logged in {os.path.relpath(path, a.root)} under {date}")
    return 0


# --------------------------------------------------------------------------- plan / apply

TYPE_HEURISTICS = [
    (r"\b(play|run)books?\b", "Playbook"),
    (r"\b(metrics?|kpis?)\b", "Metric"),
    (r"\b(adrs?|decisions?)\b", "Decision Record"),
    (r"\b(glossary|definitions?)\b", "Glossary Term"),
    (r"\b(apis?|endpoints?)\b", "API Endpoint"),
    (r"\b(tables?|datasets?|schemas?|models?)\b", "Data Asset"),
    (r"\b(how-?tos?|guides?|tutorials?)\b", "Guide"),
    (r"\bfaqs?\b", "FAQ"),
    (r"\b(meetings?|minutes|standups?|retros?)\b", "Meeting Notes"),
    (r"\b(polic(y|ies)|standards?)\b", "Policy"),
    (r"\b(process(es)?|procedures?|sops?|workflows?)\b", "Process"),
    (r"\b(specs?|specifications?|rfcs?|prds?)\b", "Specification"),
    (r"\b(changelog|release-?notes)\b", "Changelog"),
    (r"\b(readme|overview|about|intro)\b", "Overview"),
]


def infer_type(rel, fm, rules, default):
    for glob, t in rules:
        if fnmatch.fnmatch(rel, glob):
            return t, "rule"
    for k in ("kind", "category", "layout", "doc_type", "doctype"):
        if isinstance(fm.get(k), str) and fm[k].strip():
            return humanize(fm[k]).title() if fm[k].islower() else fm[k], f"existing-field:{k}"
    parts = rel.lower().split("/")
    for seg in [parts[-1]] + parts[-2::-1]:
        seg = re.sub(r"\.md$", "", seg).replace("_", " ").replace(".", " ")
        for pat, t in TYPE_HEURISTICS:
            if re.search(pat, seg):
                return t, "heuristic"
    return default, "default"


def first_sentence(body):
    s = strip_code(body)
    s = re.sub(r"<!--.*?-->", "", s, flags=re.S)
    para = []
    for line in s.splitlines():
        t = line.strip()
        if not t:
            if para:
                break
            continue
        if re.match(r"^(#|>|\||[*+-]\s|\d+[.)]\s|!\[|<|---|===|\[\^)", t):
            if para:
                break
            continue
        para.append(t)
    if not para:
        return None
    text = " ".join(para)
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"[*_]{1,3}([^*_]+)[*_]{1,3}", r"\1", text)
    text = re.sub(r"\[\^[^\]]+\]", "", text).strip()
    m = re.match(r"(.+?[.!?])(\s|$)", text)
    sent = m.group(1) if m else text
    return sent if len(sent) <= 200 else sent[:197].rstrip() + "..."


def file_time(path):
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%cI", "--", os.path.basename(path)],
                             cwd=os.path.dirname(path), capture_output=True, text=True, timeout=10).stdout.strip()
        if out:
            return utc_z(datetime.fromisoformat(out)), "git"
    except Exception:
        pass
    return utc_z(datetime.fromtimestamp(os.path.getmtime(path), timezone.utc)), "mtime"


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:40] or "source"


def parse_citations(body):
    sec = find_section(body, "citations")
    if not sec:
        return None, []
    sources, seen = [], set()
    for line in body[sec[0]:sec[1]].splitlines():
        m = re.match(r"^\s*(?:[-*+]|\d+[.)])\s+(.+)$", line)
        if not m:
            continue
        item = m.group(1).strip()
        lm = re.search(r"\[([^\]]+)\]\(([^)\s]+)\)", item)
        um = re.search(r"https?://\S+", item)
        if lm:
            title, res = lm.group(1).strip(), lm.group(2)
        elif um:
            res = um.group(0).rstrip(").,;")
            title = item.replace(um.group(0), "").strip(" -:,") or None
        else:
            title, res = None, item
        base = slug(title) if title else slug(re.sub(r"^https?://(www\.)?", "", res).rstrip("/").split("/")[-1])
        sid, n = base, 2
        while sid in seen:
            sid, n = f"{base}-{n}", n + 1
        seen.add(sid)
        e = {"id": sid, "resource": res}
        if title:
            e["title"] = title
        sources.append(e)
    return sec, sources


def looks_like_prose(d):
    s = strip_code(d.body)
    if isinstance(fm_dict(d).get("type"), str):
        return True
    items = len(LIST_LINK_RE.findall(s))
    prose = sum(1 for l in s.splitlines() if l.strip() and not re.match(r"^\s*(#|[*+-]\s|\d+[.)]\s)", l))
    return items == 0 and prose > 0


def cmd_plan(a):
    b = Bundle(a.root, a.exclude)
    rules = []
    for r in a.rule:
        if "=" not in r:
            sys.exit(f"--rule must look like 'GLOB=Type' (got {r!r})")
        g, t = r.split("=", 1)
        rules.append((g.strip(), t.strip()))
    files = []
    for rel, d in sorted(b.docs.items()):
        name = posixpath.basename(rel)
        item = {"path": rel, "actions": [], "notes": []}
        if name in RESERVED:
            bad_log = name == "log.md" and any(
                not DATE_RE.match(h.strip()) for h in re.findall(r"^##[ \t]+(.+)$", strip_code(d.body), re.M))
            if (name == "index.md" and looks_like_prose(d)) or bad_log:
                stem = posixpath.basename(posixpath.dirname(rel)) or "bundle"
                inbound = sum(1 for o in b.docs.values() if any(
                    resolve(o.rel, u) == rel for u in LINK_RE.findall(strip_code(o.body))))
                item["actions"].append("review-reserved")
                item["suggested_rename"] = rjoin(posixpath.dirname(rel), f"{stem}-{'overview' if name == 'index.md' else 'history'}.md")
                item["rename_to"] = None
                fix = ("rewrite it as `* [Title](url) - description` sections (or run `okf.py index --force`)" if name == "index.md"
                       else "rewrite its `##` headings as YYYY-MM-DD dates, newest first")
                item["notes"].append(f"{name} is reserved (spec 3.1) but doesn't follow spec {'8' if name == 'index.md' else '9'}. "
                                     f"Either {fix}, or, if it is really a concept, set rename_to and re-run plan to give it frontmatter "
                                     f"({inbound} inbound link(s) would need updating).")
                files.append(item)
            continue
        if d.has_fm and (d.fm_error or not isinstance(d.fm, dict)):
            item["actions"].append("fix-frontmatter-manually")
            item["notes"].append(d.fm_error or "Frontmatter is not a YAML mapping.")
            files.append(item)
            continue
        fm = fm_dict(d)
        add = {}
        if not (isinstance(fm.get("type"), str) and fm["type"].strip()):
            add["type"], item["type_source"] = infer_type(rel, fm, rules, a.default_type)
        if "title" not in fm:
            add["title"] = concept_title(d)
        if "description" not in fm:
            desc = next((fm[k] for k in ("summary", "excerpt", "abstract") if isinstance(fm.get(k), str)), None) or first_sentence(d.body)
            if desc:
                add["description"] = " ".join(desc.split())
            else:
                item["notes"].append("No description could be derived; write one.")
        if isinstance(fm.get("tags"), str):
            item["fix"] = {"tags": [t.strip() for t in re.split(r"[,;]", fm["tags"]) if t.strip()]}
        if a.by and "generated" not in fm and "timestamp" not in fm:
            at, src = file_time(b.abs(rel))
            add["generated"] = {"by": a.by, "at": at}
            item["notes"].append(f"generated.at taken from {src}.")
        if add:
            item["actions"].append("add-frontmatter" if not d.has_fm else "add-fields")
            item["add"] = add
        if item.get("fix"):
            item["actions"].append("fix-fields")
        migrate = {}
        if "timestamp" in fm and "generated" not in fm:
            ts = fm["timestamp"]
            dt = parse_dt(str(ts)) or (parse_dt(str(ts) + "Z") if re.match(r"^\d{4}-\d{2}-\d{2}T[\d:.]+$", str(ts)) else None)
            if dt is None and DATE_RE.match(str(ts)):
                dt = parse_dt(f"{ts}T00:00:00Z")
            migrate["generated"] = {"by": a.by, "at": utc_z(dt) if dt else str(ts)}
            if not a.by:
                item["notes"].append("Set migrate.generated.by to an actor (e.g. human:<id>) or the timestamp migration is skipped.")
        sec, cites = parse_citations(d.body)
        if sec:
            if fm.get("sources"):
                item["notes"].append("Has both `# Citations` and `sources`; merge by hand.")
            else:
                migrate["sources"] = cites
                item["notes"].append("Citations become `sources`; add keyed footnotes ([^id]) where claims rely on them.")
        if migrate:
            item["actions"].append("migrate-v0.1")
            item["migrate"] = migrate
        if item["actions"]:
            files.append(item)
    counts = Counter(act for f in files for act in f["actions"])
    type_sources = Counter(f.get("type_source") for f in files if f.get("type_source"))
    plan = {"okf_plan": 1, "root": b.root, "created": utc_z(now_utc()), "by": a.by,
            "summary": {"files_scanned": len(b.docs), "files_to_change": len(files), "actions": dict(counts),
                        "type_sources": dict(type_sources),
                        "proposed_types": dict(Counter(f["add"]["type"] for f in files if "type" in f.get("add", {})))},
            "files": files}
    text = json.dumps(plan, indent=2, ensure_ascii=False)
    if a.out:
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(text + "\n")
        s = plan["summary"]
        print(f"plan written to {a.out}: {s['files_to_change']}/{s['files_scanned']} files to change")
        print(f"  actions: {s['actions']}")
        print(f"  proposed types: {s['proposed_types']}")
        print(f"  type sources: {s['type_sources']}  (review 'heuristic' and 'default' entries)")
    else:
        print(text)
    return 0


HEAD_KEYS = ("type", "title", "description")


def insert_fields(fm_raw, fields):
    """Insert new top-level keys without disturbing existing text: `type` first,
    title/description after the existing head keys, everything else at the end."""
    lines = fm_raw.splitlines()
    for k, v in fields.items():
        block = emit(k, v)
        if k == "type":
            lines[0:0] = block
        elif k in HEAD_KEYS:
            at = 0
            for i, line in enumerate(lines):
                if re.match(rf"^({'|'.join(HEAD_KEYS)})\s*:", line):
                    at = i + 1
                    while at < len(lines) and re.match(r"^[ \t-]", lines[at]):
                        at += 1
            lines[at:at] = block
        else:
            lines += block
    return "\n".join(lines) + "\n"


def _rebuild(fm_raw, body):
    if fm_raw and not fm_raw.endswith("\n"):
        fm_raw += "\n"
    return f"---\n{fm_raw}---\n{body}"


def cmd_apply(a):
    with open(a.plan, encoding="utf-8") as f:
        plan = json.load(f)
    root = a.root or plan["root"]
    done, skipped = 0, []
    for item in plan["files"]:
        rel = item["path"]
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            skipped.append((rel, "file no longer exists"))
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        d = parse_doc(rel, text)
        new = text
        acts = item.get("actions", [])
        add = {k: v for k, v in (item.get("add") or {}).items() if v not in (None, "")}
        if "add-frontmatter" in acts:
            if d.has_fm:
                skipped.append((rel, "already has frontmatter; re-run plan"))
                continue
            if not add.get("type"):
                skipped.append((rel, "no type in plan"))
                continue
            new = emit_block(add) + ("\n" if not d.body.startswith("\n") else "") + d.body
        elif "add-fields" in acts and d.has_fm and isinstance(d.fm, dict):
            missing = {k: v for k, v in add.items() if k not in d.fm}
            if missing:
                new = _rebuild(insert_fields(d.fm_raw, missing), d.body)
        fix = item.get("fix") or {}
        if "fix-fields" in acts and fix:
            d = parse_doc(rel, new)
            fm_raw = d.fm_raw
            for k, v in fix.items():
                fm_raw = re.sub(rf"^{re.escape(k)}\s*:.*$", lambda _m: "\n".join(emit(k, v)), fm_raw, count=1, flags=re.M)
            new = _rebuild(fm_raw, d.body) if d.has_fm else new
        mig = item.get("migrate") or {}
        if "migrate-v0.1" in acts and mig:
            d = parse_doc(rel, new)
            fm_raw, body = d.fm_raw, d.body
            g = mig.get("generated")
            if g and g.get("by") and isinstance(d.fm, dict) and "generated" not in d.fm:
                fm_raw = re.sub(r"^timestamp\s*:.*$", emit("generated", {"by": g["by"], "at": g["at"]})[0], fm_raw, count=1, flags=re.M)
            elif g:
                skipped.append((rel, "timestamp kept: migrate.generated.by not set"))
            src = mig.get("sources")
            if src and isinstance(d.fm, dict) and "sources" not in d.fm:
                fm_raw = (fm_raw if fm_raw.endswith("\n") or not fm_raw else fm_raw + "\n") + "\n".join(emit("sources", src)) + "\n"
                sec = find_section(body, "citations")
                if sec:
                    rest = body[sec[1]:].lstrip("\n")
                    body = body[: sec[0]].rstrip("\n") + ("\n\n" + rest if rest else "").rstrip("\n") + "\n"
            new = _rebuild(fm_raw, body) if d.has_fm else new
        target = item.get("rename_to")
        if new != text:
            check = parse_doc(rel, new)
            if check.fm_error or not isinstance(check.fm, dict):
                skipped.append((rel, f"result would not parse ({check.fm_error}); left untouched"))
                continue
            if not a.dry_run:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(new)
            print(f"{'would edit' if a.dry_run else 'edited'} {rel}")
            done += 1
        if target:
            tpath = os.path.join(root, target)
            if os.path.exists(tpath):
                skipped.append((rel, f"rename target {target} exists"))
            else:
                if not a.dry_run:
                    os.makedirs(os.path.dirname(tpath) or ".", exist_ok=True)
                    os.rename(path, tpath)
                print(f"{'would rename' if a.dry_run else 'renamed'} {rel} -> {target}")
                done += 1
    for rel, why in skipped:
        print(f"skipped {rel}: {why}")
    print(f"{done} change(s) {'planned' if a.dry_run else 'applied'}, {len(skipped)} skipped")
    if not a.dry_run and done:
        print("next: okf.py index ROOT && okf.py audit ROOT")
    return 0


# --------------------------------------------------------------------------- CLI


def main(argv=None):
    p = argparse.ArgumentParser(prog="okf.py", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    def with_root(sp):
        sp.add_argument("root", help="bundle root directory")
        sp.add_argument("--exclude", action="append", default=[], metavar="GLOB",
                        help="skip files/dirs matching GLOB (repeatable; dot-dirs and node_modules are always skipped)")

    s = sub.add_parser("audit", help="check conformance and lint")
    with_root(s)
    s.add_argument("--json", action="store_true", help="machine-readable output (all findings)")
    s.add_argument("--strict", action="store_true", help="exit 1 on warnings too")
    s.add_argument("--min-severity", choices=["error", "warning", "info"], default="warning")
    s.add_argument("--max-per-code", type=int, default=15, help="cap printed findings per code (0 = no cap)")
    s.add_argument("--now", help="override 'now' for staleness (ISO 8601 with offset)")
    s.set_defaults(fn=cmd_audit)

    s = sub.add_parser("index", help="generate/refresh index.md files")
    with_root(s)
    s.add_argument("--group-by", choices=["none", "type"], default="none")
    s.add_argument("--okf-version", help=f"okf_version for the root index (default: keep existing, else {OKF_VERSION})")
    s.add_argument("--no-version", action="store_true", help="don't declare okf_version")
    s.add_argument("--force", action="store_true", help="overwrite hand-curated index.md files too")
    s.add_argument("--check", action="store_true", help="don't write; exit 1 if any index is out of date")
    s.set_defaults(fn=cmd_index)

    s = sub.add_parser("init", help="scaffold a bundle")
    s.add_argument("root")
    s.add_argument("--okf-version", default=OKF_VERSION)
    s.add_argument("--date", help="YYYY-MM-DD for the initialization log entry")
    s.set_defaults(fn=cmd_init)

    s = sub.add_parser("new", help="create a concept")
    s.add_argument("root")
    s.add_argument("path", help="concept path relative to root, e.g. playbooks/freshness-alert.md")
    s.add_argument("--type", required=True)
    s.add_argument("--title")
    s.add_argument("--description")
    s.add_argument("--resource")
    s.add_argument("--tags", help="comma-separated")
    s.add_argument("--status", choices=STATUSES)
    s.add_argument("--by", help="actor for generated.by: <producer>/<version>, human:<id>, or process:<id>")
    s.add_argument("--stale-after", help="ISO 8601 datetime with offset")
    s.add_argument("--runtime", help="required for Attested Computation")
    s.add_argument("--log", action="store_true", help="add a Creation entry to the root log.md")
    s.set_defaults(fn=cmd_new)

    s = sub.add_parser("log", help="add a log.md entry")
    s.add_argument("root")
    s.add_argument("--dir", help="directory (relative to root) whose log.md to write; default root")
    s.add_argument("--kind", default="Update", help="leading bold word, e.g. Update, Creation, Deprecation")
    s.add_argument("--message", required=True)
    s.add_argument("--date")
    s.set_defaults(fn=cmd_log)

    s = sub.add_parser("plan", help="propose edits to make a folder conformant")
    with_root(s)
    s.add_argument("--out", help="write plan JSON here (default: stdout)")
    s.add_argument("--rule", action="append", default=[], metavar="GLOB=Type", help="force a type for matching paths (repeatable, first wins)")
    s.add_argument("--default-type", default="Reference", help="type when nothing else matches (default: Reference)")
    s.add_argument("--by", help="actor to record in generated.by (omit to skip provenance)")
    s.set_defaults(fn=cmd_plan)

    s = sub.add_parser("apply", help="apply a reviewed plan")
    s.add_argument("plan")
    s.add_argument("--root", help="override the root recorded in the plan")
    s.add_argument("--dry-run", action="store_true")
    s.set_defaults(fn=cmd_apply)

    a = p.parse_args(argv)
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
